### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by XuMengren** [ghtz08/kuguo-kgm-decoder#2]
➜  kuguo-kgm-decoder-master cargo build --release
warning: associated functions `new` and `decodeable_length_interval` are never used
  --> src/decoder/mod.rs:15:8
   |
14 | pub trait Decoder<'a>: Sized + Read {
   |           ------- associated functions in this trait
15 |     fn new(origin: impl Read + 'a) -> Self;
   |        ^^^
16 |     fn try_new(origin: impl Read + 'a) -> Option<Self>;
17 |     fn decodeable_length_interval() -> (u64, u64);
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `kgm-decoder` (bin "kgm-decoder") generated 1 warning
    Finished `release` profile [optimized] target(s) in 0.08s
➜  kuguo-kgm-decoder-master kgm-decoder <src/assets/test.kgm>
zsh: parse error near `\n'
➜  kuguo-kgm-decoder-master 

根据你的使用方式运行不了啊，能帮我看看是怎么回事吗

**Comment by ghtz08** [comment]
路径名不要用`<`和`>`括起来，一般命令参数用以下规则：
`key`：这是一个 flag 参数，这个参数的名字就是 key，不能用其它符号代替。
`[abc|def]`：这是一个可选参数，可选值是 abc 或者 def，可以没有如果有那只能是 abc 或者 def。
`<describe>`：这是一个值参数，`<>`里是对这个值的描述，应该用一个具体的值代替包括`<>`的部分。
